name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Verify PR title
      env:
        PR_TITLE: ${{ toJson(github.event.pull_request.title) }}
      run: |
        /bin/bash ./bin/verify-pr-title.sh "$PR_TITLE"

  test:
    needs: verify
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install
      run: npm ci

    - name: Lint
      run: npm run lint

    - name: Typecheck
      run: npm run tsc

    - name: Build
      run: npm run build --if-present
      env:
        CI: true

# TODO: add tests, with coverage report artifact
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/persisting-workflow-data-using-artifacts
